# Generate doxygen file into docs/html directory. 
# Then, push it to the gh-pages contents. 
# The project needs to configure to upload the gh-pages branch. 
# Refer https://github.com/DenverCoder1/doxygen-github-pages-action

name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - temp
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token:  ${{ secrets.DOXYGEN_GH_PAGE }}
          branch: gh-pages
          folder: docs/html
          config_file: Doxyfile
